pipeline {
    agent {
        node {
            label 'maven'
            
        }
    }

    stages {
        stage('git clone') {
            steps {
               git branch: 'main', url:'https://github.com/Kajald-21/tweet-trend.git'
            }
        }
    }
}
