---
- hosts: jenkins-master
  become: true
  tasks:

  - name: Install Java (Amazon Linux)
    yum:
      name: java-11-amazon-corretto
      state: present

  - name: Add Jenkins repository
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import Jenkins GPG key
    rpm_key:
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      state: present

  - name: Install Jenkins
    yum:
      name: jenkins
      state: present

  - name: Start Jenkins service
    service:
      name: jenkins
      state: started

  - name: Enable Jenkins at boot
    service:
      name: jenkins
      enabled: true
